### ISSUE TITLE
Would you please rename the mod to Notebook instead?

### ISSUE THREAD

**Issue by ardissaps** [JWGardiner/Minecraft-Coordinate-Book#18]
It can cause confusioon with[ Coordinate Book Mod](https://modrinth.com/mod/coordinate-book)

**Comment by JWGardiner** [comment]
It's only called coordinate book in it's source code and here on GitHub, on it's major download sites now

It was already called "Vanilla Notebook" on curseforge.

https://modrinth.com/mod/notebook

I will not change the GitHub, since most people looking for the mod will be searching on either modrinth or curseforge.

I'll leave this issue open for now in case you want to add anything
